# Generated by Django 5.2.7 on 2025-10-30 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='full_name',
        ),
        migrations.AlterModelOptions(
            name='userauth',
            options={'verbose_name_plural': 'Base User'},
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('userauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=100)),
                ('vehicle_plate', models.CharField(max_length=50)),
                ('availability_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Rider Profile',
                'db_table': 'rider_profile',
            },
            bases=('account.userauth',),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('userauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('shop_name', models.CharField(max_length=150)),
                ('shop_type', models.CharField(max_length=100)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Vendor Profile',
                'db_table': 'vendor_profile',
            },
            bases=('account.userauth',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
                'db_table': 'user_profile',
            },
            bases=('account.userauth',),
        ),
    ]
