# Generated by Django 5.2.7 on 2025-10-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userauth_image_remove_userauth_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userauth',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
