# Generated by Django 5.2.7 on 2025-11-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_full_name_userauth_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauth',
            options={'verbose_name_plural': 'All User'},
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
