# Generated by Django 5.2.7 on 2025-11-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userauth_options_riderprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Customer Profile'},
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
