# Generated by Django 5.2.7 on 2025-11-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_options_riderprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='userauth',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
