# Generated by Django 5.2.7 on 2025-11-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_riderprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER'), ('VENDOR', 'VENDOR'), ('RIDER', 'RIDER')], default='USER', max_length=20),
        ),
    ]
