# Generated by Django 5.2.7 on 2025-11-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userauth_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_image/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_license',
            field=models.ImageField(blank=True, null=True, upload_to='shop_license/'),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='shop_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
