# Generated by Django 5.2.7 on 2025-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_riderprofile_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userauth',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
