# Generated by Django 5.2.7 on 2025-11-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_riderprofile_image_remove_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='loaction_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='location_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
