# Generated by Django 5.2.7 on 2025-11-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userauth_loaction_lat_userauth_location_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='loaction_lat',
            new_name='location_lat',
        ),
    ]
