# Generated by Django 5.2.7 on 2025-11-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_loaction_lat_userauth_location_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
