# Generated by Django 5.2.7 on 2025-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userauth_current_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='location_long',
        ),
        migrations.AddField(
            model_name='userauth',
            name='current_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
