# Generated by Django 5.2.7 on 2025-11-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_userauth_location_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='delivery_address',
        ),
    ]
