# Generated by Django 5.2.7 on 2025-11-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_address_userprofile_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='total_rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='total_rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
