# Generated by Django 5.2.7 on 2025-12-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
