# Generated by Django 5.2.7 on 2025-11-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='driver',
            new_name='rider',
        ),
    ]
