# Generated by Django 5.2.7 on 2025-11-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_driver_order_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rider_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
