# Generated by Django 5.2.7 on 2025-12-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_delivery_fee_order_final_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
