# Generated by Django 5.2.7 on 2025-11-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_stock_product_stock_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='weight_kg',
        ),
    ]
